AWS:
  ACCESS_KEY_ID: ASIAVFTSQ26XBILOJAPN
  SECRET_ACCESS_KEY: L+nb+aZWVFJYkXOXDzDUEmZm/9bxua/3bJox/PUX
  SESSION_TOKEN: IQoJb3JpZ2luX2VjEOb//////////wEaCXVzLXdlc3QtMiJGMEQCIAe2P1taQmgHWQL4xG6NEyPAWckM/qF0qvVw9Dmyiu7vAiBcNO4B4n8PterekIuC99d+OhFndgOoremuFtTbKI17hyqZAwh/EAAaDDM1NTY0ODcyMjg2MiIMT+5kcbz1b2i/YaBtKvYCKhStO38Fbx3B7CCdCxV72K1Zzj5QSQHpFpF2b/mcTcmGZkfJhvnNvdmx8bwAh/orikZ+guVHExZbMPiiAFiBIADP+3IHS1svxNgx6kU26YkhrDX4HfXjBxyWKjEWHAOoEAtteYQ6+HOjO1Vi8BkFJrsoVWBAy+s8iuA/lXViSrMWhydiQC9n9gQGUcPOHy4I1an45lguKY5It0Gq8fki+GTE6qXpnMQfh1+kBs5Bv5wKE3Wi5yvCQ86wVyxs0Sw5QWRjgd1IyZ6ergpebZViqUE78slh5CiTBEnS7kR1SJ0h7BPdj7PDhKRO3OSSaABNh1vTBRqA+0Jtms/FFsPM4edpEzE8U1bU8y8APh2hdydqy2/03dWplercvXaSczCPyf07pX93QZd2T815YzznUgevNZrrxCBhYLkQrgwh/3emMkkTtJLNYKPXMq7/+td7wIjhAIAJ22xQ9pHWf7KOTokSeF1ofrpPGiPDy7Gy1SbHKmJ6iIowpM7crAY6pwFFHpXr3K9VWR7xCEEIiP8JT9em0Gr/OJxtL21pcjXirBQFskdvhI7m1p6dQzV7VrPIRurDHDD5ul5uEP7XqhaYbxUZLxEDjq72T3cJ65ngezZNHuQDAGXK+CgFCFX7YzBuzcPNYban2kbGIvqAst1PFq8/X3KbhVesHD3H3g8W79YyTWq4PXT7hv8mm4PqWjE42ciwhuijNDTHYE1tMOVgwXXtSATgYw==
  REGION: us-east-1

VALIDATION: 
  PERMISSIONS:
    StackSet-EMR-Role:
      - CloudWatchFullAccess
      - AmazonEC2FullAccess
      - AmazonS3FullAccess
      - AmazonSSMFullAccess
      - AmazonSageMakerFullAccess
      - AmazonElasticMapReduceRole

INFRA:
  GITHUB_ORGANIZATION: DISHDevEx
  GITHUB_REPOSITORY: maria-luminex-test
  GITHUB_WORKFLOW: create-emr-cft.yml
  GITHUB_EVENT_TYPE: create-emr-cft

ETL:
  S3_INPUT_BUCKET_NAME:
  AWS_REGION:
  TRANSFORMATION_FOLDER_PATH: DISHDevEx/luminex-transformation
  S3_BUCKET_INPUT_PATH:
  S3_BUCKET_TEMP_OUTPUT_PATH:
  S3_BUCKET_FINAL_OUTPUT_PATH:
  TRANSFORMATION_FOLDER: scripts/transformation/
  BOAT: luminex
  INPUT_FOLDER:

EXPERIMENT:
  META:
    NAME: MyFirstExperiment
  MODEL:
    FAMILY: resnet
    N_LAYERS: 151
    NESTED_FAMILY:
      ITEMS:
        - CloudWatchFullAccess
        - AmazonEC2FullAccess
  TRAINING:
    BATCH_SIZE: 256
    EPOCHS: 10000