name: Deploy EMR Cluster using CFT template

on:
  repository_dispatch:
    types: [create-emr-cft]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout files
        run: |
          ls -l

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.client_payload.inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.client_payload.inputs.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.client_payload.inputs.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.AWS_Region || 'us-east-1' }}

      - name: Install Boto3
        run: pip install boto3

      - name: Validate Stack
        id: validate-stack
        env:
          aws-access-key-id: ${{ github.event.client_payload.inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.client_payload.inputs.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.client_payload.inputs.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.AWS_Region || 'us-east-1' }}
          stack-name: ${{ github.event.client_payload.inputs.stack-name }}
        run: |
          echo $stack-name &&
          python luminex/validation/stack_name_validator.py 2> validation_error.txt || true

      - name: Deploy EMR cluster
        id: deploy-emr
        run: |
          stack_id=$(aws cloudformation create-stack \
            --stack-name ${{ github.event.client_payload.inputs.stack-name }} \
            --template-body file://./infrastructure/create-emr-cft.yml \
            --parameters file://./infrastructure/config_parameter.json \
            --role-arn \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            | jq -r '.StackId') 2> deployment_error.txt && echo "CloudFormation stack ID: $stack_id" || true

      - name: Process Errors in Python
        run: |
          validation_error = open("validation_error.txt", "r").read()
          deployment_error = open("deployment_error.txt", "r").read()

          # Process validation_error and deployment_error in your Python script
          # You can use them in your Python logic or print them for further analysis
          print(f"Validation Error: {validation_error}")
          print(f"Deployment Error: {deployment_error}")
