name: Terminate EMR Cluster

on:
  workflow_dispatch:

jobs:
  terminate-emr:
    runs-on: ubuntu-latest
    needs: create-emr.deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.AWS_Region || 'us-east-1' }}

      - name: Terminate EMR cluster
        run: |
          
          aws emr terminate-clusters --cluster-ids ${{ needs.create-emr.deployment.outputs.emr-cluster-id }}
